# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: commit_message
  value: "${Build.SourceVersionMessage}"
- name: test_message
  value: "Test Message"

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo "Master Commit Message: ${commit_message}"
    echo "Master Test Message: ${test_message}"
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
